#!/usr/bin/env python3

import os
import io
import json

    city = open("Cities.json", "r")
    cityDict = json.loads(city.read())
    #loop through the file
    l = r.readline().strip()
    while (l) :
  
